### PR TITLE
Add repr() to argument for regex search method to resolve data type err

### PR DESCRIPTION
**Pull request by ehilfer**

### CODE REVIEW

**Comment by vrajat** [comment]
Thanks for the contribution. Can you tell me why you made this change? Did you get an error when running the app?

**Comment by ehilfer** [comment]
Yes, I was seeing an exception during deep (data) scan on some of our Postgres tables due to string formatting or type conversion errors.

**Comment by vrajat** [comment]
Hmm - I dont think this is the right fix for the problem. `repr` will return the python type of `m.data_type` which is always a string. Instead the problem is with the content of the variable. For context, `m` stores all the information about column in a table. So there is a problem with the Postgres type. Can you file an issue with the full stack trace and also the data type of the column that is causing the error?

**Comment by ehilfer** [comment]
Issue created: https://github.com/tokern/piicatcher/issues/177

**Review by vrajat — APPROVED** [review]
This is a good check to have for multiple reasons. Thanks!

**Pull request merged**
