### PR TITLE
Add Dockerfile for piicatcher

### PR DESCRIPTION
**Pull request by n2taylor**
I wanted to run piicatcher without having to install dependencies locally, so I created a Dockerfile for it. Feedback appreciated.

### CODE REVIEW

**Comment by vrajat** [comment]
This looks great. I see that you have also used layers to keep size of the container small. Happy to accept the contribution. Thanks!

I have one question - How will you pass parameters or config to piicatcher?

**Comment by n2taylor** [comment]
command line params can just be appended onto the `docker run` command:

```
docker run 2317377d1e5b files --path /tmp
╭─────────────┬─────────────┬─────────────╮
│    Path     │  Mime/Type  │     pii     │
├─────────────┼─────────────┼─────────────┤
...
```

**Comment by vrajat** [comment]
Merged. Thanks for the contribution. I'll look into automatically uploading a container to dockerhub for every release. 

Can you take this survey? https://forms.gle/Ns6QSNvfj3Pr2s9s6 It will help me understand how you are using piicatcher.

**Comment by n2taylor** [comment]
Sure thing!

**Pull request merged**
